"use client";
import { useState } from "react";
import { Bot, Check, GripVertical, Plus, Send, Sparkles, Trash2 } from "lucide-react";
import { AppFrame } from "@/components/layout/AppSidebar";

type Draft = { id: number; stem: string; choices: string[]; correct: number; explanation: string };
const initial: Draft = { id: 1, stem: "다음 작품에 나타난 화자의 태도로 가장 적절한 것은?", choices: ["대상에 대한 그리움을 드러내고 있다.", "현실을 비판적으로 바라보고 있다.", "미래에 대한 기대를 표현하고 있다.", "자신의 처지를 체념하고 있다."], correct: 0, explanation: "시어의 반복과 어조를 중심으로 화자의 정서를 파악한다." };
export function QuestionEditor() {
 const [drafts, setDrafts] = useState<Draft[]>([initial]); const [prompt, setPrompt] = useState(""); const [sent, setSent] = useState(false);
 const update = (id: number, key: keyof Draft, value: string | number | string[]) => setDrafts((list) => list.map((d) => d.id === id ? {...d, [key]: value} : d));
 const add = () => setDrafts((list) => [...list, { ...initial, id: Date.now(), stem: "새 문항의 지문을 입력하세요.", choices: ["선지 1", "선지 2", "선지 3", "선지 4"] }]);
 const ask = () => { if (!prompt.trim()) return; setSent(true); setTimeout(() => { setDrafts((list) => [...list, { ...initial, id: Date.now(), stem: `AI 제안 문항: ${prompt}`, choices: ["핵심 개념을 올바르게 적용한 내용", "개념을 일부 혼동한 내용", "지문과 관계없는 내용", "조건을 반대로 해석한 내용"] }]); setPrompt(""); }, 450); };
 return <AppFrame title="문항 에디터"><main className="editor-page"><section className="editor-main"><div className="editor-title"><div><span className="eyebrow">문제집 편집</span><h1>2026 수능 국어 · 문학</h1></div><button className="button primary"><Check size={16}/> 저장하기</button></div>{drafts.map((draft, index) => <article className="draft-card panel" key={draft.id}><div className="draft-head"><span><GripVertical size={17}/> 문항 {index + 1}</span><button onClick={() => setDrafts((l) => l.filter((d) => d.id !== draft.id))} aria-label="문항 삭제"><Trash2 size={16}/></button></div><label>지문</label><textarea className="field editor-text" value={draft.stem} onChange={(e) => update(draft.id, "stem", e.target.value)}/><label>선지</label><div className="editor-choices">{draft.choices.map((choice, i) => <div key={i}><button onClick={() => update(draft.id, "correct", i)} className={`radio ${draft.correct === i ? "checked" : ""}`}>{i + 1}</button><input className="field" value={choice} onChange={(e) => update(draft.id, "choices", draft.choices.map((c, n) => n === i ? e.target.value : c))}/></div>)}</div><label>해설</label><textarea className="field editor-text small" value={draft.explanation} onChange={(e) => update(draft.id, "explanation", e.target.value)}/></article>)}<button className="add-question" onClick={add}><Plus size={18}/> 문제 +</button></section>
 <aside className="ai-chat panel"><div className="ai-head"><span><Sparkles size={17}/> AI 출제 도우미</span><small>beta</small></div><div className="chat-body"><div className="ai-message">원하는 주제, 난이도, 출제 포인트를 알려주세요. 문항 초안을 바로 에디터에 추가해드릴게요.</div>{sent && <div className="user-message">문항을 추가했어요. 계속 다듬어 보세요.</div>}</div><div className="chat-input"><textarea value={prompt} onChange={(e) => setPrompt(e.target.value)} placeholder="예: 현대시 화자의 태도를 묻는 상 난이도 문항 1개"/><button className="button primary" onClick={ask}><Send size={16}/></button></div><div className="chat-suggestions"><button onClick={() => setPrompt("문학 고난도 문항을 만들어줘")}>문학 고난도</button><button onClick={() => setPrompt("오답 선지를 더 그럴듯하게 만들어줘")}>선지 다듬기</button></div></aside></main></AppFrame>;
}
