"use client";
import { useState } from "react";
import Link from "next/link";
import { ArrowRight, Bot, Check, PencilLine, Sparkles } from "lucide-react";
import { AppFrame } from "@/components/layout/AppSidebar";

const subjects: Record<string, Record<string, string[]>> = { "수능": { "국어": ["문학", "독서", "언어와 매체"], "수학": ["미적분", "확률과 통계", "기하"] }, "내신": { "국어": ["문학", "화법과 작문"], "사회": ["사회·문화", "생활과 윤리"] } };
export function WorkbookBuilder() {
  const [step, setStep] = useState(1); const [exam, setExam] = useState("수능"); const [category, setCategory] = useState("국어"); const [subject, setSubject] = useState("문학"); const [type, setType] = useState("객관식 중심"); const [difficulty, setDifficulty] = useState("중"); const [made, setMade] = useState(false);
  const categories = Object.keys(subjects[exam]); const currentSubjects = subjects[exam][category] ?? [];
  return <AppFrame title="문제집 만들기"><main className="page-content builder"><div className="stepper"><span className={step === 1 ? "on" : "done"}>{step > 1 ? <Check size={14}/> : "1"} 기본 정보</span><i/><span className={step === 2 ? "on" : ""}>2 상세 조건</span><i/><span>3 문제집 생성</span></div>
    <section className="builder-card panel">{step === 1 ? <><span className="eyebrow">Step 1</span><h1 className="title">어떤 시험을 준비하고 있나요?</h1><p className="subtle">문제집에 맞는 과목 범위를 먼저 정해주세요.</p><div className="selection-block"><label>시험 카테고리</label><div>{Object.keys(subjects).map((x) => <button onClick={() => {setExam(x); setCategory(Object.keys(subjects[x])[0]);}} className={`select-card ${exam === x ? "selected" : ""}`} key={x}>{x}</button>)}</div></div><div className="selection-block"><label>대분류</label><div>{categories.map((x) => <button onClick={() => setCategory(x)} className={`select-card ${category === x ? "selected" : ""}`} key={x}>{x}</button>)}</div></div><div className="selection-block"><label>소과목</label><div>{currentSubjects.map((x) => <button onClick={() => setSubject(x)} className={`select-card ${subject === x ? "selected" : ""}`} key={x}>{x}</button>)}</div></div><button className="button primary next-button" onClick={() => setStep(2)}>상세 조건 설정 <ArrowRight size={17}/></button></> : <><span className="eyebrow">Step 2</span><h1 className="title">문항의 결을 맞춰볼까요?</h1><p className="subtle">{exam} · {category} · {subject} 기준으로 생성됩니다.</p><div className="selection-block"><label>문항 구성</label><div>{["객관식 중심", "주관식 포함", "주관식만"].map((x) => <button onClick={() => setType(x)} className={`select-card ${type === x ? "selected" : ""}`} key={x}>{x}</button>)}</div></div><div className="selection-block"><label>선지 개수</label><div>{["4지선다", "5지선다", "혼합"].map((x) => <button className="select-card" key={x}>{x}</button>)}</div></div><div className="selection-block"><label>난이도</label><div>{["하", "중", "상", "혼합"].map((x) => <button onClick={() => setDifficulty(x)} className={`select-card ${difficulty === x ? "selected" : ""}`} key={x}>{x}</button>)}</div></div><button className="button" onClick={() => setStep(1)}>이전</button><button className="button primary next-button" onClick={() => setMade(true)}>문제집 생성 <ArrowRight size={17}/></button></>}
    </section>{made && <section className="track-area"><div className="made-head"><div><span className="eyebrow">Ready</span><h2>문제집을 만들 준비가 됐어요.</h2></div><button onClick={() => setMade(false)} className="button">조건 수정</button></div><div className="track-grid"><div className="track ai-track"><Sparkles/><h3>AI와 대화하며 만들기</h3><p>주제와 출제 의도를 말하면 AI가 문항 초안을 제안합니다.</p><Link className="button primary" href="/studio/editor?mode=ai">AI 대화 시작 <Bot size={16}/></Link></div><div className="track"><PencilLine/><h3>직접 문항 만들기</h3><p>빈 문항부터 시작해 지문, 선지, 해설을 자유롭게 작성합니다.</p><Link className="button" href="/studio/editor">에디터 열기 <ArrowRight size={16}/></Link></div></div></section>}</main></AppFrame>;
}
